apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: kafka-factory
  labels:
    app.kubernetes.io/part-of: kafka-factory-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafka-factory-prometheus
  labels:
    app.kubernetes.io/part-of: kafka-factory-demo
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kafka-factory-prometheus
  labels:
    app.kubernetes.io/part-of: kafka-factory-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kafka-factory-prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: kafka-factory
