apiVersion: apps/v1
kind: Deployment
metadata:
  name: factory-producer
  namespace: kafka-car-factory
  labels:
    app: factory-producer
    app.kubernetes.io/part-of: kafka-car-factory-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factory-producer
  template:
    metadata:
      labels:
        app: factory-producer
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3002"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: factory-producer
          image: factory-producer
          ports:
            - name: control
              containerPort: 3002
          env:
            - name: KAFKA_BROKERS
              value: factory-kafka-kafka-bootstrap.kafka-car-factory.svc.cluster.local:9092
            - name: USE_APICURIO_REGISTRY
              value: "true"
            - name: CONTROL_PORT
              value: "3002"
            - name: APICURIO_REGISTRY_URL
              value: http://apicurio-registry.kafka-car-factory.svc.cluster.local:8080
            - name: NODE_ENV
              value: production
          resources:
            requests:
              memory: 128Mi
              cpu: "100m"
            limits:
              memory: 256Mi
              cpu: "300m"
          livenessProbe:
            exec:
              command:
                - node
                - -e
                - "process.exit(0)"
            initialDelaySeconds: 30
            periodSeconds: 30
