apiVersion: v1
kind: Service
metadata:
  name: battery-producer
  namespace: kafka-car-factory
  labels:
    app: battery-producer
    app.kubernetes.io/part-of: kafka-car-factory-demo
spec:
  selector:
    app: battery-producer
  ports:
    - name: http
      port: 8086
      targetPort: 8086

