apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: broker
  namespace: kafka-factory
  labels:
    strimzi.io/cluster: factory-kafka
    app.kubernetes.io/part-of: kafka-factory-demo
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: true
  resources:
    requests:
      memory: 1Gi
      cpu: "500m"
    limits:
      memory: 2Gi
      cpu: "1000m"
  template:
    pod:
      metadata:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "9404"
          prometheus.io/path: "/"
