apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: kafka-factory
  labels:
    app.kubernetes.io/part-of: kafka-factory-demo
type: Opaque
stringData:
  username: factory
  password: factory
  jdbc-url: jdbc:postgresql://postgres.kafka-factory.svc.cluster.local:5432/factory_analytics

